<a href="https://colab.research.google.com/github/lovelyoyrmia/machine-learning-notebook/blob/main/image_preprocessing_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import google.colab as gc

In [5]:
gc.files.upload()

Saving cat-323262__480.webp to cat-323262__480.webp


{'cat-323262__480.webp': b'RIFF\x18\xa1\x00\x00WEBPVP8 \x0c\xa1\x00\x00\xd0i\x02\x9d\x01*\xd0\x02\xe0\x01>I"\x8eE\xa2\xa2-\xa4$r\xea\xf9\xb0\t\tenn\xf7\x9bNlw\xa5\xa6U\nb\xb4H\xd2_m\xdak\xc6\x87\xbf\xfcM\xbbM1Yx\x06\xa3\xbf\xb9g\x8f\xd8\x0e\xd6L\x1f\x86\xbf\x03\xe5\xa1\xec}\xe3\xbdH\xff\x16\xf3t\xea\xd3\xce\xf7\xe7)\xe9\x01\xa6\x8fW\xc9\xe6]m\xfeq\xf6\xbf\x8c\x0e^\xde\xeb\xe0G\xe2\x8f\xfb\xff\xc0\xf6\x9f\xfd\xff\x81?<u\x1a\xc6\x1f\xf9\x9d\xe2\xfcw\xfc\x7fC/\x87\xf3s\xc4\xbf\xe6=C\x7f\xc7\x7f\xbc\xf5\xbf\xfew\x90\xd7\xf4?\xe0{\x07\xfe\x9a\xf4\x8d\xd3\xf7\xec?\xef}\x8b\xfc\xb3\xff\xff\xfb\xd8\xfd\xc3\xff\xff\xef9\xfb\x89\xff\xfc\xadu\xac\xf9\xa7S^@b\x07\x98L\xec\x05\x9d\xdf\xfb\x0be8P]\xfbu\x97h&$\xafm4@\x9f+\rq\xe0+\x02\xeb\xd6\xd8\x82\x9bV@3\x1cA\x01\x06\ne\x889\x0fv\x16 Fh\xb3\xed\xf1)\x00t>\x9c\x8bT\xfa:\x1d}\x8a\xf6\xdd\xc5\x15\xb2\xcbVIM\xd4Dg\xef\xb7\xeb\x14\x99\x8d\xdf\xf0\x92@L\xb2\xfdk[\x15R8wh\xb5l0\xc0@\xfdr\xa8\xc1\xf9\xd6lN\xba\x13\xb3\xed\xd3\xf5\xfb5N\xd8+5\x17w_\xb2h\x9b

In [1]:
from tensorflow.keras.preprocessing import image

In [6]:
img = image.load_img('/content/cat-323262__480.webp', target_size=(224, 224))

In [7]:
img_array = image.img_to_array(img)

In [8]:
img_array

array([[[119., 189., 179.],
        [121., 191., 181.],
        [124., 194., 184.],
        ...,
        [103., 150., 141.],
        [102., 151., 141.],
        [103., 152., 142.]],

       [[116., 186., 176.],
        [119., 189., 179.],
        [123., 193., 183.],
        ...,
        [103., 150., 141.],
        [102., 151., 141.],
        [103., 152., 142.]],

       [[114., 184., 174.],
        [116., 186., 176.],
        [121., 191., 181.],
        ...,
        [103., 150., 141.],
        [102., 151., 141.],
        [104., 151., 142.]],

       ...,

       [[175., 167., 161.],
        [175., 167., 161.],
        [178., 169., 163.],
        ...,
        [174., 119.,  65.],
        [196., 141.,  87.],
        [183., 128.,  74.]],

       [[174., 162., 152.],
        [175., 163., 153.],
        [181., 169., 159.],
        ...,
        [192., 139.,  89.],
        [175., 121.,  71.],
        [180., 127.,  77.]],

       [[185., 171., 159.],
        [188., 174., 163.],
        [190., 1

In [9]:
img_array.shape

(224, 224, 3)

In [10]:
import numpy as np
expand_image = np.expand_dims(img_array, axis=0)
expand_image

array([[[[119., 189., 179.],
         [121., 191., 181.],
         [124., 194., 184.],
         ...,
         [103., 150., 141.],
         [102., 151., 141.],
         [103., 152., 142.]],

        [[116., 186., 176.],
         [119., 189., 179.],
         [123., 193., 183.],
         ...,
         [103., 150., 141.],
         [102., 151., 141.],
         [103., 152., 142.]],

        [[114., 184., 174.],
         [116., 186., 176.],
         [121., 191., 181.],
         ...,
         [103., 150., 141.],
         [102., 151., 141.],
         [104., 151., 142.]],

        ...,

        [[175., 167., 161.],
         [175., 167., 161.],
         [178., 169., 163.],
         ...,
         [174., 119.,  65.],
         [196., 141.,  87.],
         [183., 128.,  74.]],

        [[174., 162., 152.],
         [175., 163., 153.],
         [181., 169., 159.],
         ...,
         [192., 139.,  89.],
         [175., 121.,  71.],
         [180., 127.,  77.]],

        [[185., 171., 159.],
       

In [11]:
expand_image.shape

(1, 224, 224, 3)

In [13]:
import tensorflow
from tensorflow.keras.layers import GlobalMaxPool2D
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

In [14]:
model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
model.trainable = False

model = tensorflow.keras.Sequential([
  model,
  GlobalMaxPool2D()
])

94781440/94765736 [==============================] - 2s 0us/step


In [17]:
preprocessed_img = preprocess_input(expand_image)
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[-132.81702, -161.337  , -252.04001],
         [-130.81702, -159.337  , -250.04001],
         [-127.81701, -156.337  , -247.04001],
         ...,
         [-170.81702, -200.337  , -268.04   ],
         [-170.81702, -199.337  , -269.04   ],
         [-169.81702, -198.337  , -268.04   ]],

        [[-135.81702, -164.337  , -255.04001],
         [-132.81702, -161.337  , -252.04001],
         [-128.81702, -157.337  , -248.04001],
         ...,
         [-170.81702, -200.337  , -268.04   ],
         [-170.81702, -199.337  , -269.04   ],
         [-169.81702, -198.337  , -268.04   ]],

        [[-137.81702, -166.337  , -257.04   ],
         [-135.81702, -164.337  , -255.04001],
         [-130.81702, -159.337  , -250.04001],
         ...,
         [-170.81702, -200.337  , -268.04   ],
         [-170.81702, -199.337  , -269.04   ],
         [-169.81702, -199.337  , -267.04   ]],

        ...,

        [[-150.81702, -183.337  , -196.04001],
         [-150.81702, -183.337  , -196.04001]

In [18]:
model.predict(preprocessed_img).shape

(1, 2048)

In [19]:
model.predict(preprocessed_img).flatten().shape

(2048,)

In [21]:
from numpy.linalg import norm

In [23]:
model.predict(preprocessed_img).flatten() / norm(model.predict(preprocessed_img).flatten())

array([0.00619071, 0.01992397, 0.01503636, ..., 0.00179454, 0.0129433 ,
       0.01090339], dtype=float32)

In [25]:
norm(model.predict(preprocessed_img).flatten())

334.51166

In [24]:
np.sqrt(np.dot(model.predict(preprocessed_img).flatten(), model.predict(preprocessed_img).flatten()))

334.51166